In [23]:
#question1
import numpy as np
array=np.array([1,2,3])
list1= array.tolist()
print(array)
print(list1)

[1 2 3]
[1, 2, 3]


In [3]:
#question2
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
s=np.trace(a)
print(a)
print(s)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
15


In [16]:
#question3
import numpy as np
a=np.array([[1,2],[3,5]])
x=2
print(a)
print('values greater than x: ',a[a>x])

[[1 2]
 [3 5]]
values greater than x:  [3 5]


In [19]:
#question4
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[10,11,12]])
c=a+b
print(c)

[[ 8 10 12]
 [14 16 18]]


In [22]:
#question5
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print(a)
b=a-a.mean(axis=1,keepdims=True)
print(b)

[[1 2 3]
 [4 5 6]]
[[-1.  0.  1.]
 [-1.  0.  1.]]
